name: lightning-flow-scanner
on:
  workflow_dispatch:
  pull_request:
jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Version
        uses: actions/checkout@v4
      - name: Scan Salesforce Flows
        uses: RubenHalman/lightning-flow-scanner-action@1.0.0
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}